gems:
  - jekyll-asciidoc
  - jekyll-assets
  - jekyll-paginate 


title: ssaOrvibo
description: documentation du plugin Orvibo.
url: jeedom.com


source: run
destination: _site
exclude:
  - index.html



asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - icons=font
    - imagesdir=images
















 







 





